### ISSUE TITLE
Simulation Review

### ISSUE THREAD

**Issue by AkshayaAcharya** [Abhilol123/V_Labs#1]
Hello,

We have gone through your Simulator. @Abhilol123 

Suggestions from our side and Prof. KV Sir is that:
1. To have same font styles, color as in [https://mdmv-nitk.vlabs.ac.in/exp6/index.html#](https://mdmv-nitk.vlabs.ac.in/exp6/index.html#). So you can use stylesheet (momstyle.css) that is given sample template, we shared. You can refer the sample simulation how the stylesheet is included.
2.  The parameters and variables you display like omega should have units mentioned along with it and precision can be upto 4 digits.
3. Queries about the experiment you can approach Rohit Kushawaha

We were not able to access this link [https://abhilol123.github.io/Base-Exitation-VLABS/](https://abhilol123.github.io/Base-Exitation-VLABS/)

You can convey these suggestions to your team mates.

**Comment by Abhilol123** [comment]
Hello

I have Implemented the changes mentioned.

Here are the links to the experiments:
Base Excitation link: https://abhilol123.github.io/Base-Excitation-VLABS/
Rotating Unbalance: https://abhilol123.github.io/Rotating-Unbalance-VLABS-/

Regards
Abhinav
